# This config is only provisional
# It is used to design the BaseTracker class

streamline:
    # Mandatory
    nii_file:
    n_fibers:
    block_size:
    n_last_incoming:
    wm_mask:
    step_size:
    # Optional
    seeds:
    reseed_endpoints:
    out_name:
