#Examples of config settings
#===========================
#Uncomment the example that you want to run
#Leave the first two lines of the example commented, though
#The second line of each example provides the command for the terminal

#Example 1
#smt run --config .config.yaml -X data/X_train.npy -a fit_transform
class: ml_project.models.feature_selection.RandomSelection
params:
  n_components: 1000
  random_state: 37

#Example 2 (Warning: might exceed your memory)
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#class: ml_project.models.regression.KernelEstimator

#Example 3
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#class: ml_project.pipeline.Pipeline
#params:
#  class_list:
#    - class: ml_project.models.feature_selection.RandomSelection
#      params:
#        random_state: 37
#        n_components: 1000
#    - class: sklearn.linear_model.LinearRegression

#Example 4
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#class: ml_project.gridsearch.GridSearchCV
#params:
#  est_class: ml_project.pipeline.Pipeline
#  est_params:
#    - class: ml_project.models.feature_selection.RandomSelection
#      params:
#        random_state: 37
#    - class: sklearn.linear_model.LinearRegression
#  param_grid:
#    RandomSelection__n_components:
#      - 100
#      - 1000
#      - 10000
#  cv:
#    class: sklearn.model_selection.KFold
#    params:
#      n_splits: 3
#      shuffle: True
#      random_state: 37

#class: ml_project.models.regression.ExampleTF
#params:
#  input_fn_config:
#    batch_size: 64
#    num_epochs: 5
#    shuffle: True
#    queue_capacity: 1000
#    num_threads: 1
#  config:
#    save_summary_steps: 10
#    tf_random_seed: 42
#    save_checkpoints_steps: 100
#    #save_checkpoints_secs:
#    keep_checkpoint_max: 5
#    log_step_count_steps: 10
#  params:
#    learning_rate: 0.005
#    hooks:
#      - type: SummarySaverHook
#        params: {name: mean_output, op: scalar, save_steps: 10}