# smt run -r "KOLN T2 conversion" --config configs/mri_pipeline/koln_t2.yaml -a transform
class: src.data.mri_pipeline.MriPreprocessingPipeline
params:
  path: /local/KOLN/T2
  files_glob: /local/KOLN/T2/raw/*/*/*.nii.gz
  extract_image_id_regexp: .*/(\d+)/(\d+)_t2\.nii\.gz
  regexp_image_id_group: null
  regexp_patient_id_group: 2
  set_all_single_class: PD
  steps:
    - type: template_registration
      subfolder: _registered_2mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_2mm.nii.gz
      overwrite: False
    - type: exec_command
      subfolder: _brain_extracted_2mm
      command: 'fslmaths {mri_image} -mas {mask} {mri_output}'
      mask: data/raw/templates/MNI152_T2_2mm_brain_mask.nii.gz
      overwrite: False
  split_train_test:
    random_seed: 0
    pkl_prefix: KOLN_T2_
    test_images_def:
      - class: PD
        count: 50
  filter_xml: null
  shard:
    num_workers: 1
    worker_index: 0
