# smt run -r "PPMI T2 conversion" --config configs/mri_pipeline/ppmi_t2.yaml -a transform
class: src.data.mri_pipeline.MriPreprocessingPipeline
params:
  path: /local/PPMI
  files_glob: /local/PPMI/raw/*/*/*/*/*.nii
  extract_image_id_regexp: .*S(\d+)_I(\d+)\.nii
  regexp_image_id_group: 2
  steps:
    # Manual brain extraction and then align [1mm]
    - type: brain_extraction
      from_subfolder: raw
      subfolder: _brain_manual_extracted
      options: '-f 0.35 -g 0.1'
      images_bet_params: data/raw/ppmi/images_bet.json
      overwrite: False
    - type: template_registration
      from_subfolder: _brain_manual_extracted
      subfolder: _brain_manual_extracted_registered_1mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_1mm_brain.nii.gz
      overwrite: False
    # Manual brain extraction and then align [2mm]
    - type: template_registration
      from_subfolder: _brain_manual_extracted
      subfolder: _brain_manual_extracted_registered_2mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_2mm_brain.nii.gz
      overwrite: False
    # Substantia Nigra extraction
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn
      crop_x: [65, 115] # 50
      crop_y: [85, 125] # 40
      crop_z: [44, 71]  # 27
      overwrite: False
    # Shifted crops
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x0_y1_z1
      crop_x: [15, 65]
      crop_y: [85, 125]
      crop_z: [44, 71]
      overwrite: False
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x2_y1_z1
      crop_x: [115, 165]
      crop_y: [85, 125]
      crop_z: [44, 71]
      overwrite: False
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x1_y0_z1
      crop_x: [65, 115]
      crop_y: [45, 85]
      crop_z: [44, 71]
      overwrite: False
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x1_y2_z1
      crop_x: [65, 115]
      crop_y: [125, 165]
      crop_z: [44, 71]
      overwrite: False
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x1_y1_z0
      crop_x: [65, 115]
      crop_y: [85, 125]
      crop_z: [17, 44]
      overwrite: False
    - type: image_crop
      from_subfolder: _brain_manual_extracted_registered_1mm
      subfolder: _brain_manual_extracted_registered_1mm_sn_x1_y1_z2
      crop_x: [65, 115]
      crop_y: [85, 125]
      crop_z: [71, 98]
      overwrite: False
    # Align and then extract brain [1mm]
    - type: template_registration
      from_subfolder: raw
      subfolder: _registered_1mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_1mm.nii.gz
      overwrite: False
    - type: exec_command
      from_subfolder: _registered_1mm
      subfolder: _brain_extracted_1mm
      command: 'fslmaths {mri_image} -mas {mask} {mri_output}'
      mask: data/raw/templates/MNI152_T2_1mm_brain_mask.nii.gz
      overwrite: False
    # Align and then extract brain [2mm]
    - type: template_registration
      from_subfolder: raw
      subfolder: _registered_2mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_2mm.nii.gz
      overwrite: False
    - type: exec_command
      from_subfolder: _registered_2mm
      subfolder: _brain_extracted_2mm
      command: 'fslmaths {mri_image} -mas {mask} {mri_output}'
      mask: data/raw/templates/MNI152_T2_2mm_brain_mask.nii.gz
      overwrite: False
  filter_xml:
    files: /local/PPMI/raw/*_I*.xml
    xml_image_id: ./project/subject/study/imagingProtocol/imageUID
    xml_class: ./project/subject/researchGroup
    xml_patient_id: ./project/subject/subjectIdentifier
    filters:
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Weighting']
        value:
            eq: T2
      # Skip FLAIR images (these are not really T2 images)
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: FLAIR
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: Flair
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: flair
      # Only take the 75% images with the highest Z dimension (computed to about 32)
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix Z']
        value:
            gt: 30
      # Remove some weirdly bugged images
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix X']
        value:
            lt: 600
  shard:
    num_workers: 1
    worker_index: 0
