# smt run -r "PPMI T2 conversion" --config configs/mri_pipeline/ppmi_t2.yaml -a transform
class: src.data.mri_pipeline.MriPreprocessingPipeline
params:
  path: /local/PPMI
  files_glob: /local/PPMI/raw/*/*/*/*/*.nii
  extract_image_id_regexp: .*S(\d+)_I(\d+)\.nii
  regexp_image_id_group: 2
  steps:
    - type: brain_extraction
      subfolder: 01_brain_extracted
      options: '-f 0.35 -g 0.1'
      images_bet_params: data/raw/ppmi/images_bet.json
      overwrite: False
    - type: template_registration
      subfolder: 02_registered
      cost: normcorr
      searchcost: normcorr
      overwrite: False
      mri_template: data/raw/templates/MNI152_T2_2mm_brain.nii.gz
  split_train_test:
    random_seed: 0
    pkl_prefix: PPMI_T2_NC_PD_
    test_images_def:
      - class: Control
        count: 50
      - class: PD
        count: 100
  filter_xml:
    files: /local/PPMI/raw/*_I*.xml
    xml_image_id: ./project/subject/study/imagingProtocol/imageUID
    xml_class: ./project/subject/researchGroup
    filters:
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Weighting']
        value:
            eq: T2
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: FLAIR
      # Only take the 75% images with the highest Z dimension (computed to about 32)
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix Z']
        value:
            gt: 30
      # Remove some weirdly bugged images
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix X']
        value:
            lt: 600
  shard:
    num_workers: 1
    worker_index: 0
