# smt run -r "PPMI T2 conversion" --config configs/mri_pipeline/ppmi_t2.yaml -a transform
class: src.data.mri_pipeline.MriPreprocessingPipeline
params:
  path: /local/PPMI
  files_glob: /local/PPMI/raw/*/*/*/*/*.nii
  extract_image_id_regexp: .*S(\d+)_I(\d+)\.nii
  regexp_image_id_group: 2
  steps:
    - type: template_registration
      subfolder: _registered_1mm
      cost: normcorr
      searchcost: normcorr
      mri_template: data/raw/templates/MNI152_T2_1mm.nii.gz
      overwrite: False
    - type: exec_command
      subfolder: _brain_extracted_1mm
      command: 'fslmaths {mri_image} -mas {mask} {mri_output}'
      mask: data/raw/templates/MNI152_T2_1mm_brain_mask.nii.gz
      overwrite: False
  split_train_test:
    random_seed: 0
    pkl_prefix: PPMI_T2_NC_PD_1mm_
    test_images_def:
      - class: Control
        count: 50
      - class: PD
        count: 100
  filter_xml:
    files: /local/PPMI/raw/*_I*.xml
    xml_image_id: ./project/subject/study/imagingProtocol/imageUID
    xml_class: ./project/subject/researchGroup
    xml_patient_id: ./project/subject/subjectIdentifier
    filters:
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Weighting']
        value:
            eq: T2
      # Skip FLAIR images (these are not really T2 images)
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: FLAIR
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: Flair
      - key: ./project/subject/study/imagingProtocol/description
        value:
            doesnt_contain: flair
      # Only take the 75% images with the highest Z dimension (computed to about 32)
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix Z']
        value:
            gt: 30
      # Remove some weirdly bugged images
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix X']
        value:
            lt: 600
  shard:
    num_workers: 1
    worker_index: 0
