#CUDA_VISIBLE_DEVICES=5 python run.py --config configs/example_config.yaml -S ~/entrack/data/entrack -a fit

class: src.estimator.Estimator
params:
  input_fn_config: # Parameters for input generation (gen_input_fn)
    data_generation:
      data_raw_directory: data/raw/
      data_converted_directory: data/ready/
      train_database_file: train.tfrecord
      test_database_file: test.tfrecord
      image_shape:
        - 256
        - 256
        - 128
      dataset_compression: GZIP
      test_set_size_ratio: 0.2
      test_set_random_seed: 0
      data_sources:
        - name: KOLN_T1
          glob: data/raw/KOLN_T1/*/*/*.nii.gz
          features_from_filename:
            regexp: .*/(\d+)/(\d+)_t1\.nii\.gz
            features_group:
              study_image_id: 1
              study_patient_id: 2
          patients_features: data/raw/KOLN_PATIENTS/patients.csv

    data_streaming:
      dataset:
        - call: repeat
          count: 10
        - call: prefetch
          buffer_size: 200
        - call: shuffle
          buffer_size: 100
          seed: 0
        - call: map
          num_parallel_calls: 8
        - call: batch
          batch_size: 8
  params: # Params for model (model_fn)
    predicted_feature: age
    predicted_feature_avg: 63.7
    log_loss_every_n_iter: 1
  config: #TODO: What is this for?
    save_summary_steps: 1
    tf_random_seed: 42
    save_checkpoints_steps: 100
    #save_checkpoints_secs:
    keep_checkpoint_max: 5
    log_step_count_steps: 100
