# smt run -r "PPMI conversion" --config configs/mri_pipeline.yaml -S /local/dhaziza/data -a transform
# Preprocess PPMI data
class: src.data.mri_pipeline.MriPreprocessingPipeline
params:
  path: /local/PPMI
  files_glob: /local/PPMI/raw/*/*/*/*/*.nii
  extract_image_id_regexp: .*S(\d+)_I(\d+)\.nii
  regexp_image_id_group: 2
  params:
    brain_extraction:
      frac_intens_thres: 0.35
      bias: True
      overwrite: False
    template_registration:
      cost: normcorr
      searchcost: normcorr
      overwrite: False
      mri_template: data/raw/templates/MNI152_T2_1mm_brain.nii.gz
  filter_xml:
    files: /local/PPMI/raw/*_I*.xml
    xml_image_id: ./project/subject/study/imagingProtocol/imageUID
    filters:
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Weighting']
        value:
            eq: T2
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix Z']
        value:
            lt: 50
      - key: ./project/subject/study/imagingProtocol/protocolTerm/protocol[@term='Matrix X']
        value:
            st: 600
  shard:
    num_workers: 1
    worker_index: 0
